version: '3.7'
services:
  back:
    profiles:
      - "dev"
    container_name: back
    build: 
      context: back/
      target: "dev"
    volumes:
      - ./back/src:/app/src
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379

  back-prod:
    profiles:
      - "prod"
    container_name: back-prod
    build: 
      context: back/
      target: "prod"
    env_file:
      - .env
  styletts2:
    container_name: styletts2
    image: r8.im/adirik/styletts2@sha256:dd4d03b097968361dda9b0563716eb0758d1d5b8aeb890d22bd08634e2bd069c
    restart: always
    profiles:
      - "prod"
    ports:
      - 5007:5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

